# Generated by Django 4.2.6 on 2023-11-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('cabaña_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='cabañas/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.cabaña')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.cabaña')),
            ],
        ),
    ]
